Added cleanup function to execute before stopping

diff --git a/wfs b/wfs
--- a/wfs
+++ b/wfs
@@ -7,7 +7,7 @@
 # Licence = GNU GPL
 #
 
-VERSION=2.03
+VERSION=2.04
 
 CONFIG=/etc/wfs
 CONFIG_FILE="$CONFIG/wfs.conf"
@@ -73,12 +73,12 @@ log () {
                         fi
                         log2syslog "$TYPE" "$TYPE $MSG"
                     fi
-                    
+
                     ;;
         "INFO" )
                     if [ "$QUIET" = "0" ] && [ "$DEBUG" = "1" ]
                     then
-                        echo "$DATE $MSG" 
+                        echo "$DATE $MSG"
                     fi
                     log2syslog "$TYPE" "$TYPE $MSG"
                     ;;
@@ -147,7 +147,7 @@ route_del () {
 display_header () {
 
     log INFO "------------------------------"
-    log INFO " WAN Failover Script $VERSION" 
+    log INFO " WAN Failover Script $VERSION"
     log INFO "------------------------------"
     log INFO " Primary gateway: $PRIMARY_GW"
     log INFO " Secondary gateway: $SECONDARY_GW"
@@ -177,11 +177,11 @@ test_single_target () {
 
         if [ "$TARGETS_FAILED" -lt "$THRESHOLD" ]
         then
-            ((TARGETS_FAILED++)) 
+            ((TARGETS_FAILED++))
         fi
         TEST_INTERVAL=1
     else
-        if [ "$TARGETS_FAILED" -gt "0" ] 
+        if [ "$TARGETS_FAILED" -gt "0" ]
         then
             ((TARGETS_FAILED--))
         fi
@@ -233,9 +233,9 @@ check_wan_status () {
     if [ "$TARGETS_FAILED" -ge "$THRESHOLD" ] && [ "$ACTIVE_CONNECTION" = "PRIMARY" ]
     then
 	switch
-    elif [ "$ACTIVE_CONNECTION" = "SECONDARY" ] 
+    elif [ "$ACTIVE_CONNECTION" = "SECONDARY" ]
     then
-        if [ "$TARGETS_FAILED" = "0" ] 
+        if [ "$TARGETS_FAILED" = "0" ]
         then
 	    switch
         fi
@@ -291,6 +291,36 @@ start_wfs () {
     done
 }
 
+stop_wfs () {
+    log INFO "Got SIGTERM, cleaning and exiting."
+    TARGETS=`cat "$TARGETS_FILE"`
+
+    kill `cat $PIDFILE`
+    rm $PIDFILE
+
+    if [ ! -z "$TARGETS" ]
+    then
+        for x in $TARGETS
+        do
+            log DEBUG "Removing static route for host $x"
+            route del -host "$x" gw "$PRIMARY_GW" >> /dev/null 2>&1
+        done
+    fi
+
+    exit 0
+}
+
+# cleanup works only if $DAEMON is 1
+if [ "$DAEMON" = "1" ]
+then
+    trap stop_wfs SIGINT SIGTERM
+fi
+
+if [ "$1" == "--stop" ]
+then
+    stop_wfs
+    exit 0
+fi
 
 if [ "$DAEMON" = "0" ]
 then
